Several DB2 HADR improvements (#532)
* Bugfix sub_iscsi_nsg_arm_id variable

Error: A local value with the name "sub_iscsi" has not been declared

* Add boolean to configure pacemaker for Azure scheduled events

By default the boolean is set to true.

* Add custom pacemaker NFS filesystem and SAP monitor timeouts

When using a custom NFS solution different time-outs may be required.

Refactored the cluster-Suse tasks so that it utilizes the calculated filesystem timeout and
SAP resource monitor timeout from the 5.6.1-set_runtime_facts task

* Use virtual_host names for DB2 HADR local host name configuration

* Remove tags from ignore_changes for Linux dbserver

* Add SSL certificate generation and distribution for virtual_hostname

* Encrypt communication between HADR Primary and Standby Instances