PR for v3.10.0.0 (#509)
* Name rationalization

* Add support for multiple IP ranges

* Using a list

* adress space check

* change the address space to list

* use the correct output

* Use the renamed output storageaccount_resourcegroup_name

* Don't perform deployment if not logged on as SPN

* format

* simplify network logic

* Fix the logic for deployer configuration

* Fix deployer and flatten the list of vnets

* Fix the list of vnets

* remove the set statements

* Version update and fault domain counter

* Update the template

* Web App updates

* Variable renames

* Update pipeline

* Package updates

* Add support for multiple address ranges

* Change HTML IDs

* deployment task

* Update Azure Identity

* More informative task names

* Feng shui

* change the dns creation logic

* Fixes for IPs

* Default upgrade packages to false

* Switch to use instance metadata

* Add support for extending packages, mounts etc

* Rel 9.2 support

* Add support for dynamically retrieval of SWPM10

* hdbuserstore updates

* pacemaker updates

* Load Balancer timeout updates

* Format the Terraform files, add support for tags for all resources

* Start documentation of variables

* Add support for providing tags for all resources

* Support deployerless deployments

* Add missing tags

* Web App updates (tag support)

* Add a dependency on the private end point

* Add dependency for container

* Work on the dependency map

* Add a dependency on the storage account network rules

* Make the public access same for both storage accounts

* change the dependency order

* store the state file if failure when removing

* Adding the missing parameters

* Set permissions on variable groups

* Fix the Invoke-Restmethod call

* Allow resetting of PAT

* Fix typo

* Resetting of PAT

* allow reusing of repo

* Add permissions to pipelines

* Simplify the query

* Add a pause

* Remove default access for all pipelines

* Don't show Invoke-RestMethod response

* Add pipelines permissions for pool

* Don't set permissions on pools (yet)

* Add permissions on agent pools

* Use the queue id and not the pool ID

* Add more info

* Final version for next release

* prepare for release 3.9.3.0

* install lint 6.20.3 for the workflow as we are not ready to 6.21 yet.

* suppress tracing when checking variables

* Lint fixes

* Linting

* remove extended character

* Pull in main

* Several improvements and additions for deploying DB2 (#496)

* Bugfix nproc unlimited for dbsidadm group, not db2sidadm group

* Use virtual_host from hostvars (inventory) for DB2 installation

* Fixed DB2 log_dir mountpoint

DB2 log_dir was mounted on /log/SID/dir instead of /db2/SID/log_dir

* Fix Agent_IP variable for sap_library

* Remove become and orchestration user for delegated VmAgentActions tasks

* Improve 2.10-sap-notes tasks

* Optimize SAP OS USERS and Group Creation (user_nw) tasks

* Remove unused input-api variables

* Add custom virtual_hostname variabels for db, ers, scs and pas

* Add vars for ASCS/ERS NFS filesystem devices when not using AFS or ANF

* Bugfix data source azuread_service_principal

Error: Unsupported argument on imports.tf line 49, in data "azuread_service_principal" "sp": client_id = local.spn.client_id
An argument named "client_id" is not expected here.

one of `application_id,display_name,object_id` must be specified

* Contain setting of HANA schema name to only execute when deploying HANA

* alingment on task and set execution bit for the acss-registration shell script.

* Deployer updates (code formatting)

* Library code formatting

* Add the ability to deploy without a transport volume

* Retain the disk name

* Web App updates

* Custom repository support

* Custom package support

* Custom logical volume support

* PAS and APP install variable updates

* Add support for custom exports

* Add support for custom mounts

* Add the observer

* Use _arm_client_id and not _AgentIP

(cherry picked from commit 80e79a55ef4dc199a5e79e685df3ffd45cd8c4a9)

* Missing tags + simplify ppg and avset calculation

* Don't create PPG if there are no resources in it

* ppg creation logic

* PPG Logic troubleshooting

* More PPG troubleshooting

* Fix the AVset for non ppg deployments

* Dont get the schema when not using HANA

* Add iSCSI devices

* iSCSI updates

* Add iSCSI packages and services

* Missing quote

* missing comma

* ISCSI group

* Use workload zone sid

* Don't fail if zypper returns 103

* use different variables

* create the flag directory

* Add iSCSI Server configuration

* Run as root

* rename folder

* restore name

* Don't fail on rc == 1

* Add logic for detecting if changed

* Web App updates

* Terraform fixes

* update nic name

* updated the boolean variables

* Add rescue task for update on SUSE

* Add the tags to the utility VMs

* Removed faulty character

* Troubleshoot failed when

* Add environment variable         ZYPP_LOCK_TIMEOUT: 20

* Linting fixes

* change failed_when

* More linting

* ignore return codes

* Use zypper to perform first run

* Linting

* Add a ignore_errors

* Remove line

* Remove the upgrade tasks

* Don't show the result

* remove the when statement

* Add iSCSI Servers to output

* Add the missing parameter

* Change SCSI outputs

* concatenate

* Debug

* Add the ability to provide a User assigned identity to the VM

* Update variable

* remove the duplicate

* testing the outputs

* Use the variable directly

* Test the iSCSI

* test the outputs

* testing

* store the iSCSI server names in a list

* DB Cluster

* add the ability to assign user assigned identity

* testing

* add the scope

* Remove the extra variables

* Only scs

* testing

* Add the cluster variables

* Add support for bring your own scaleset

* Add Pickers for user assigned identities and VMSS

* Remove old samples

* Control iSCSI DHCP

* Fix the two broken boolean variables

* DNS updates

* DNS logic

* Feng shui

* Terraform updates

* Don't create admin nsg if no admin subnet

* Get the Private DNS zones from custom naming

* Naming updates

* remove the Private DNS Zone names

* Move zone names to variable

* Use local variable

* rename variable

* Use app subnet

* Use default values for private_link_service_network_policies_enabled

* Small tweaks

* update parameter file

* Add the "@"

* Web Application updates

* Bump up Ansible version

* Change the distro

* Update output

* set the computer name

* Pipeline update

* add the DB iSCSI

* Shared Disk output

* Order the parameters

* HA flag

* Add the documentation

* Use the dictionary

* Use the override parameters

* We don't need the access token

* Get the token

* Add a resource lock for the agent VMs

* Add support for providing additional users for RBAC controlled key vaults

* push changes for configure deployer

* sleep for the package manager to finish execution

* Bug Fix - ensure sapmtn_volume_size is used

Ensure that sapmnt_volume_size is used to size the volume when NFS_provider is NONE on the scs VM.
Keep a sensible default when sapmnt_volume_size is not defined.

* fix code alignment in iscsi tasks and AUTOMATIC_RECOVER=false.

* fix identation

* Deployer updates

* Library updates

* Landscape updates

* SAP System updates

* Web App updates

* introducing some new changes based on feedback and feature development

* Squashed commit of the following:

commit 450084112fdbf720788125aa599b81faafd1f997
Author: Kimmo Forss <kimforss@microsoft.com>
Date:   Wed Nov 8 21:48:51 2023 +0200

    Web App updates

commit 9d94b1ff2087b6541e0ae7d20adb9f9906f3dc67
Author: Kimmo Forss <kimforss@microsoft.com>
Date:   Wed Nov 8 14:49:52 2023 +0200

    Change the permissions for the sync script

commit 80e79a55ef4dc199a5e79e685df3ffd45cd8c4a9
Author: Kimmo Forss <kimforss@microsoft.com>
Date:   Tue Oct 31 10:42:18 2023 +0200

    Use _arm_client_id and not _AgentIP

* template updates

* Fix PATH variable in configure_deployer.sh.tmpl

* comment out argcomplete

* update version label

* remove duplicate

* Bring in SBD updates

* Use scs_lb_ip

* Fix the variable

* update template

* Bump up SKUS

* Ensure we use the right variable from the sap-parameters to define the usrsap volume group when running NFS_provider NONE (#508)

* Remove the dependency on EPEL

* add missing colons

* Bring the internal changes

* Addd network REPO

* Tweak the SLES code

* Tweak script for SLES

* remove the az update

* add the repo check

* Don't fail when adding repo

* version dictionary

* Terraform feng shui

* RHEL updates

* preparation for v3.10.0.0

* Add yaml[indentation]

* Updates for configuring the deployer

* vEnv

* Ansible version

* Disk log tests for sybase

* push changes

* remove

* changes to sybase configuration

* skip indentation checks

* Linting fixes

* jinja[spacing]

* Linting

* Update .ansible-lint

* linting

* linting

* lint

---------

Co-authored-by: Kimmo Forss <kimforss@microsoft.com>
Co-authored-by: Harm Jan Stam <harmjan+git@harmjan.com>
Co-authored-by: Steffen Bo Thomsen <steffenbothomsen@gmail.com>
Co-authored-by: Kimmo Forss <kimmo.forss@microsoft.com>